### ISSUE TITLE
Inconsistent sigma value with raw literature (ffnonbonded.itp)

### ISSUE THREAD

**Issue by KnightWE** [thomasunderwood/ClayFF#1]
Dear Tom,

I am a master student in Chemistry in VUB(a Belgium university in Brussels), and I am also trying to implement ClayFF in GROMACS. Thanks for your excellent work and sharing them with everyone via Github. 

But I found the sigma value in "ffnonbonded.itp" doesn't consist of the raw literature. There is always a scale factor of around 1.12. Did you do some special treatment for sigmas for some reasons? 

For example,
name     sigma(nm,your file)      Do(Angstrom, literature) 
ao              0.479430                         4.7943
st               0.330200                         3.7064
mgo          0.526400                         5.9090

Looking forward to hearing from you.

Best Regards,
KnightWE, from Brussels.

**Comment by thomasunderwood** [comment]
Hey KnightWE, sorry for the delayed response.

You ask a good question, and I'm glad that your checking my input parameters.
The scale factor of 1.12 is related to the different forms of the LJ potential written in the original ClayFF paper compared to the form used in GROMACS.

If look at the wikipedia page on the LJ potential (https://en.wikipedia.org/wiki/Lennard-Jones_potential), the original ClayFF paper uses the second form using r_m, whist GROMACS uses the first form with sigma. There is a factor of 1.22 between these two numbers.

On a similar note, the harmonic bond terms (bonds and angles) have a factor 2 difference between the original ClayFF paper and GROMACS. There is therefore a factor 2 difference in these input parameters too.

Hope this helps,
Tom
